version: '3'
services:
  neutron:
    image: alioth:nightly
    container_name: alioth
    volumes:
      - "./config.yaml:/app/config/config.yaml"
      - "./alioth.log:/app/alioth.log"
    environment:
      - TZ=Asia/Shanghai
    restart: always
    network_mode: "host"