name: build and push to aliyun
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login
        run: |
          docker version
          docker login --username=${{ secrets.ALIYUN_USERNAME }} --password=${{ secrets.ALIYUN_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
      - name: Build and Push
        run: |
          docker build -t registry.cn-hangzhou.aliyuncs.com/ns_zyzy/alioth:$IMAGE_TAG .
          docker push registry.cn-hangzhou.aliyuncs.com/ns_zyzy/alioth:$IMAGE_TAG
